#!/usr/bin/env node
/**
 * Test script to verify PR creation postAction works correctly
 * Tests developTicketAndCreatePR.js in isolation
 */

// Mock DMtools MCP tools
global.cli_execute_command = function(args) {
    const { execSync } = require('child_process');
    console.log('[CLI]', args.command);
    try {
        const output = execSync(args.command, {
            cwd: process.cwd(),
            encoding: 'utf8',
            stdio: ['pipe', 'pipe', 'pipe']
        });
        return output;
    } catch (error) {
        console.error('[CLI ERROR]', error.message);
        throw error;
    }
};

global.jira_post_comment = function(args) {
    console.log('[MOCK] jira_post_comment:', args.key);
    console.log('[MOCK] Comment:', args.comment);
};

global.jira_assign_ticket_to = function(args) {
    console.log('[MOCK] jira_assign_ticket_to:', args.key, '→', args.accountId);
};

global.jira_add_label = function(args) {
    console.log('[MOCK] jira_add_label:', args.key, '→', args.label);
};

global.jira_remove_label = function(args) {
    console.log('[MOCK] jira_remove_label:', args.key, '→', args.label);
};

global.file_read = function(args) {
    const fs = require('fs');
    const path = require('path');
    const filePath = path.resolve(process.cwd(), args.path);
    console.log('[FILE] Reading:', filePath);
    return fs.readFileSync(filePath, 'utf8');
};

// Load the postAction module
const postAction = require('./agents/js/developTicketAndCreatePR.js');

// Prepare test data
const testTicket = {
    key: 'TEST-123',
    fields: {
        summary: 'Test PR creation after fixing script wrapper bug',
        description: 'Testing postAction in isolation'
    }
};

const testParams = {
    ticket: testTicket,
    response: 'Test response (not used, read from outputs/response.md)',
    initiator: 'test-user-id',
    metadata: {
        contextId: 'test_pr_creation'
    },
    inputFolderPath: 'input/TEST-123'
};

// Ensure outputs/response.md exists
const fs = require('fs');
const path = require('path');

const outputsDir = path.join(process.cwd(), 'outputs');
if (!fs.existsSync(outputsDir)) {
    fs.mkdirSync(outputsDir, { recursive: true });
}

const responseFile = path.join(outputsDir, 'response.md');
const prBody = `# Test PR Description

This is a test PR to verify that PR creation works correctly after fixing the script wrapper output parsing bug.

## Changes
- Added test line to README.md

## Testing
- Testing postJSAction (developTicketAndCreatePR.js) in isolation
- Verifying cleanCommandOutput() function works correctly

## Expected Behavior
- ✅ Branch name should be clean (no "Script started" garbage)
- ✅ PR should be created successfully
- ✅ PR URL should be extracted from gh output

🤖 Generated by AI Teammate Test
`;

fs.writeFileSync(responseFile, prBody);
console.log('✅ Created outputs/response.md');

// Run the postAction
console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('🧪 Running postAction test...');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

try {
    const result = postAction.action(testParams);

    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('✅ Result:', JSON.stringify(result, null, 2));
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    if (result.success) {
        console.log('🎉 Test PASSED!');
        console.log('PR URL:', result.prUrl);
        console.log('Branch:', result.branchName);
        process.exit(0);
    } else {
        console.error('❌ Test FAILED:', result.error);
        process.exit(1);
    }
} catch (error) {
    console.error('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.error('❌ Test FAILED with exception:', error);
    console.error('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
    process.exit(1);
}
