/**
 * Greeting module - provides Hello greeting and page title for the landing page.
 * Node.js module - use greeting-browser.js in browser (generated by scripts/build-greeting-browser.js).
 */
function getGreeting() {
    return 'Hello';
}

function getPageTitle() {
    return getGreeting() + ' Jira Diff';
}

function attachToGlobal(globalObj) {
    globalObj.getGreeting = getGreeting;
    globalObj.getPageTitle = getPageTitle;
}

module.exports = { getGreeting, getPageTitle, attachToGlobal };
